version: '3'
services:
  mariadb:
    image: bitnami/mariadb:latest
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=user
      - MARIADB_DATABASE=tarea06
    networks:
      - laravel-network
    ports:
      - 3307:3306

  laravel:
    image: bitnami/laravel:latest
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=user
      - DB_DATABASE=tarea06
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mariadb_data:
